services:
  - type: web
    name: agentai-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "PYTHONPATH=.uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
